### ISSUE TITLE
Error: Cannot find module 'grunt-legacy-log-utils'

### ISSUE THREAD

**Issue by pmackay** [daigofuji/jekyll-foundation-5-starter#11]
Running `grunt` I'm seeing this error:

```
Error: Cannot find module 'grunt-legacy-log-utils'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pmackay/dev/waste-standards/jekyll-foundation-5-starter/node_modules/grunt/node_modules/grunt-legacy-log/index.js:25:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

I was able to do npm install for that module but then a bunch of others were missing. Several manual steps and I got it working so grunt would run. Would be great if this worked out the box.

**Comment by daigofuji** [comment]
Assuming updated node_module will fix this issue. If something like this happens in the future, please run `npm install` then `bower install`.
